services:
  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "15678:5678" # Dashboard UI N8N
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=n8n
      - N8N_BASIC_AUTH_PASSWORD=n8n
    volumes:
      - ./n8n_data:/home/node/.n8n

volumes:
  n8n_data:
