services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - '5678:5678' # Dashboard UI N8N
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_SECURE_COOKIE=false
      - GENERIC_TIMEZONE=UTC+7
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
